### PR TITLE
Use ?nil when checking for integer.

### LINKED ISSUE #81: Django app fails when specifying Postgres port
When I specify a port for postgres, URI parse `:5432` as an integer.
The code however checks to see if the value is `empty?`, which causes the following error:

```ruby
:15:in `block in parse_database_url': undefined method `empty?' for 5432:Integer (NoMethodError)
	from delme.rb:4:in `tap'
	from delme.rb:4:in `parse_database_url'
	from delme.rb:19:in `<main>'
```

### PR DESCRIPTION
**Pull request by maraca**
Fixes #81

### CODE REVIEW

**Comment by coderanger** [comment]
Lulz, copy pasta fail. Thanks!

**Comment by maraca** [comment]
Thanks for the super prompt review! Would you mind bumping the minor version of the metadata so we can push a new release? Thanks!

**Comment by coderanger** [comment]
I'll probably do it later tonight after the tests finish. As a workaround you can use the non-URL form for now.

**Comment by maraca** [comment]
Sure thing. Again, thanks for being so quick on this ;)

**Pull request merged**
