### PR TITLE
Updated to work with application 4.1.4

### PR DESCRIPTION
**Pull request by blairham**

### CODE REVIEW

**Comment by jmaziarz** [comment]
+1

**Comment by DrMerlin** [comment]
+2

**Comment by lmunro** [comment]
+10000
Can someone please merge this it's been 6 months? Or at least comment why it hasn't been merged?

**Comment by paulmoon** [comment]
+1

**Comment by m01** [comment]
+1

**Comment by coderanger** [comment]
No longer relevant, application 5.0 is the one true way.

**Pull request closed without merging**
