### PR TITLE
Remove upper case of celery config template. (closes #76)

### LINKED ISSUE #76: There is a way to give celery worker parameters?
Hi,

I'm using application_celery_worker and I need to set `--concurrency` parameter, but I didn't found any place talking about parameters to celery service.

There is a way to set this parameter to celery service?

Thanks!

### PR DESCRIPTION
**Pull request by alissonperez**
Now, celery config will be with lower case settings.

Se more here: http://docs.celeryproject.org/en/latest/userguide/configuration.html#new-lowercase-settings

Please, tell me if something is strange to you guys!
Thank you!

### CODE REVIEW

**Comment by coderanger** [comment]
Celery 4.0 was just released a few weeks ago with support for this, and it will be able to read the old style for at least a major version cycle it sounds like. Making this change would remove compat with older Celery for no clear benefit at the moment. Maybe circle back on this in a year or two?

**Comment by alissonperez** [comment]
Yes, I agree with you @coderanger, no problem ! But with this changes application_celery_config will be compatible with new celery version. What do you think if we add some setting to enable this? So, keeping compatible with older and newer versions.

Thank you!

**Comment by coderanger** [comment]
It is already compatible, the Celery 4.0 release notes make it very clear that the old config options still work fine and will continue to work. Are you seeing a specific error?

**Comment by coderanger** [comment]
Going to close this out, from other questions elsewhere the error the user was seeing was due to using the wrong config option name.

**Pull request closed without merging**
